### ISSUE TITLE
Renaming the executable to stethoscope

### ISSUE THREAD

**Issue by mlkersten** [MonetDBSolutions/monetdb-stethoscope#25]

**Comment by kutsurak** [comment]
Well this changes the name of the project and means that we need to create a new project on PyPI. I *strongly* prefer not to have the users install a different project, but just upgrade their current installations. Also since this project is not autonomous but dependent on monetdb, I believe the name should reflect that.

**Comment by mlkersten** [comment]
1) the number of stethoscope users is probably less than 5 (internal), this should not block us indefinitely
2) name consistency is worth much mode
3) monetdb-stethoscope as project name to identify monetdb roots is fine.
